/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SDA9.DakouriKobri.ToDoList;

/**
 * The class App contains the main method by which the application starts running.
 *
 * @author Dakouri Maurille-Constant Kobri
 * @version 1.0
 * @since 2021.03.09
 */

public class App {
    /**
     * The main method, which is starting point of the application.
     *
     * @param args array of characters sequence passed to the main method.
     */
    public static void main(String[] args) {

        Menu menu = new Menu();
    }

}
